### ISSUE TITLE
what is port 6124

### ISSUE THREAD

**Issue by wkevils** [intelsdi-x/snap-relay#22]
Would someone be able to explain what is port 6124 which appears in  the README.md file:
"echo "test.first 13 `date +%s`"|nc -u -c localhost 6124"

Which process is assumed to be listening/running on his port?

KW

**Comment by IzabellaRaulin** [comment]
@wkevils, this is default port of Graphite. Snap-relay streams metrics from Graphite. Snap-relay documentation should be improved to indicate about that more clearly. Thank you for pointing that.
